version: "3.2"
services:
  backend:
    build: 
        context: ./
        dockerfile: ./ContinuousIntegration/Dockerfile
    image: backend
    ports:
     - "8080:8080"
     
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "80:80"